export const UPDATE_PROFILE_STATE = 'UPDATE_PROFILE_INFO';
export const GET_INITIAL_PROFILE_STATE = 'GET_INITIAL_PROFILE_STATE';
export const UPDATE_APP_STATE = 'UPDATE_APP_STATE';
export const ADD_MY_ITEM = 'ADD_MY_ITEM';
export const DELETE_MY_ITEM = 'DELETE_MY_ITEM';
export const GET_INITIAL_MYITEMS_STATE = 'GET_INITIAL_MYITEMS_STATE';
export const ACCEPT_TRADE_REQ = 'ACCEPT_TRADE_REQ';
export const DECLINE_TRADE_REQ = 'DECLINE_TRADE_REQ';
export const CANCEL_TRADE_REQ = 'CANCEL_TRADE_REQ';



